from pathlib import Path
import subprocess,base64,json
from PIL import Image,ImageDraw,ImageFont
OUT=Path(__file__).resolve().parent
FF='/opt/homebrew/bin/ffmpeg'
for folder,name in [('frames','revised'),('side_frames','side'),('baseline_frames','baseline')]:
    subprocess.run([FF,'-y','-loglevel','error','-framerate','20','-i',str(OUT/folder/'%04d.png'),'-c:v','libx264','-crf','19','-pix_fmt','yuv420p','-movflags','+faststart',str(OUT/(name+'.mp4'))],check=True)
subprocess.run([FF,'-y','-loglevel','error','-i',str(OUT/'revised.mp4'),'-filter_complex','fps=20,scale=480:-1:flags=lanczos,split[a][b];[a]palettegen=stats_mode=diff[p];[b][p]paletteuse=dither=sierra2_4a','-loop','0',str(OUT/'hammer_shoulder_polish.gif')],check=True)
frames=[1,10,16,28,34,38,58,66]
labels=['01 / SINGLE HAND','10 / REACH','16 / REGRIP','28 / DRIVE','34 / CONTACT','38 / ABSORB','58 / RECOVER','66 / RELEASE']
board=Image.new('RGB',(1440,776),'#11191e');draw=ImageDraw.Draw(board)
for i,(f,label) in enumerate(zip(frames,labels)):
    x=(i%4)*360;y=(i//4)*388
    im=Image.open(OUT/'frames'/f'{f:04d}.png').convert('RGB').resize((360,360))
    board.paste(im,(x,y));draw.text((x+12,y+367),label,fill='#dce7e7')
board.save(OUT/'keyposes.jpg',quality=92)

faceboard=Image.new('RGB',(1440,1000),'#11191e');fd=ImageDraw.Draw(faceboard)
for row,label in enumerate(['previous','polished']):
    for col,view in enumerate(['front','threequarter','side']):
        im=Image.open(OUT/f'{label}_face_{view}.png').convert('RGB').resize((480,480));faceboard.paste(im,(col*480,row*500));fd.text((col*480+12,row*500+484),label.upper()+' / '+view,fill='#dce7e7')
faceboard.save(OUT/'face_comparison.jpg',quality=92)

def data(name,mime):return 'data:'+mime+';base64,'+base64.b64encode((OUT/name).read_bytes()).decode()
html='''<!doctype html><html lang="zh-CN" translate="no"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>日鹤 · 单手扛锤与人物精修</title>
<style>*{box-sizing:border-box}body{margin:0;background:#10191e;color:#e7ece9;font:15px/1.7 -apple-system,BlinkMacSystemFont,"PingFang SC",sans-serif}main{max-width:1160px;margin:auto;padding:32px 28px 60px}a{color:#94d0c2}header{display:flex;justify-content:space-between;gap:20px;align-items:end;margin-bottom:22px}h1{font-size:30px;letter-spacing:.02em;margin:5px 0 8px}p{margin:7px 0}.eyebrow{font-size:11px;color:#97b6b7;letter-spacing:3px}header p,.muted{color:#99acb1;font-size:13px}.tag{border:1px solid #46625e;border-radius:99px;padding:5px 12px;color:#b5d7cb;font-size:12px;white-space:nowrap}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.card{background:#1a262c;border:1px solid #2b3b43;border-radius:14px;overflow:hidden}.cardtop{padding:14px 18px;display:flex;align-items:center;justify-content:space-between}.cardtop b{font-size:16px}.cardtop span{color:#91a9af;font-size:12px}video{width:100%;aspect-ratio:1;display:block;background:#263439}.toolbar{margin:22px 0;display:flex;align-items:center;gap:12px;flex-wrap:wrap}button,select{border:1px solid #405259;border-radius:7px;background:#24343a;color:#edf2ef;padding:9px 16px;font:inherit;cursor:pointer}button.primary{background:#b9d8cc;color:#18332c;border-color:#b9d8cc;font-weight:600}input{accent-color:#c1dccf;flex:1;min-width:160px}#frame{font-variant-numeric:tabular-nums;width:65px;color:#b5c9cc}#status{font-size:12px;color:#92b1b7;min-height:24px}.keys{display:flex;gap:7px;flex-wrap:wrap}.keys button{font-size:12px;padding:6px 12px}.callout{display:grid;grid-template-columns:repeat(3,1fr);gap:22px;padding:23px 0;margin:18px 0;border-top:1px solid #304049;border-bottom:1px solid #304049}.callout b{display:block;font-size:14px;margin-bottom:5px}.callout p{font-size:13px;color:#9fb1b5}h2{font-size:19px;margin:27px 0 12px}.sheet{width:100%;border-radius:10px}.sources{display:grid;grid-template-columns:1fr 1fr;gap:10px}.source{padding:14px 17px;background:#1b282e;border:1px solid #30424a;border-radius:10px}.source p{color:#9db0b5;font-size:12px}details{margin-top:22px;color:#a7bbbe;font-size:13px}summary{cursor:pointer}footer{margin-top:25px;color:#829b9e;font-size:12px}@media(max-width:700px){main{padding:20px 14px}.grid,.sources,.callout{grid-template-columns:1fr}header{display:block}h1{font-size:25px}.tag{display:inline-block;margin-top:8px}.toolbar{gap:8px}.cardtop{padding:10px 13px}}</style>
<main><header><div><div class="eyebrow">SUMMER MEMORIES / MOTION STUDY 05</div><h1>扛得住，握得稳，收得回来</h1><p>单手肩扛 → 空手接柄 → 双手下砸 → 卸力 → 回肩松手</p></div><span class="tag">可编辑动画试作 · 2026.09.21</span></header>
<div class="grid"><section class="card"><div class="cardtop"><b>A · 上一版人物与动作</b><span>3.0 秒 · 保留旧版</span></div><video id="before" muted playsinline preload="auto" src="__BASELINE__"></video></section><section class="card"><div class="cardtop"><b id="rightTitle">B · 单手肩扛精修</b><select id="view" aria-label="新版视角"><option value="main">三分之四视角</option><option value="side">横版侧视</option></select></div><video id="after" muted playsinline preload="auto" src="__REVISED__"></video></section></div>
<div class="toolbar"><button id="play" class="primary">播放对照</button><button id="reset">回到开头</button><select id="speed" aria-label="播放速度"><option value="1">1× 原速</option><option value=".5">0.5× 慢放</option></select><input id="seek" aria-label="停帧" type="range" min="0" max="71" step="1" value="0"><span id="frame">01 / 72</span></div>
<div class="keys"><button data-frame="0">肩扛 · 01</button><button data-frame="12">抓柄 · 13</button><button data-frame="21">蓄力 · 22</button><button data-frame="32">接触 · 33</button><button data-frame="35">卸力 · 36</button><button data-frame="65">松手回肩 · 66</button></div><p id="status">加载本地预览…</p>
<div class="callout"><div><b>人物继续修形</b><p>眼睑、虹膜、小高光与更细镜框；后发增加完整体积，肩肘采用混合权重与局部修形。</p></div><div><b>单手与双手有交接</b><p>空手先抬起并张开手指，13 帧跟随握点；33 帧接触靶面，61 帧解除跟随，逐渐回到单手肩扛。</p></div><div><b>连续，但仍需打磨</b><p>切换位置与朝向误差为零，握点持续跟随已验证。人物仍偏简化，关节修形和表演节奏还需精作。</p></div></div>
<p class="muted">两版均按原速播放；新版增加接柄和松手，为 3.6 秒。旧版结束后停在末帧。停帧按相同经过时间定位，非严格动作阶段对齐。</p><h2>动作的交接和余势</h2><img class="sheet" src="__SHEET__" alt="肩扛、蓄力、身体启动、加速、接触、卸力、回收关键姿势对照">
<h2>脸部与头发近景</h2><img class="sheet" src="__FACES__" alt="旧版与新版正面、三分之四、侧面头部对照"><h2>本轮补充阅读</h2><div class="sources"><div class="source"><a href="https://www.aversionofreality.com/blog/2022/4/21/custom-normals-workflow" target="_blank" rel="noopener">aVersionOfReality · 卡通明暗与法线 ↗</a><p>区分几何轮廓与受光。本輪精修脸形和肤色层次，未安装作者复杂法线系统。</p></div><div class="source"><a href="https://blenderartists.org/t/critique-a-beginners-second-stylized-character/1576380/18" target="_blank" rel="noopener">BlenderArtists · 眼睛逐轮修改 ↗</a><p>眼睑覆盖虹膜、适量高光与镜框遮挡。已读讨论，并看作者修改前后图。</p></div><div class="source"><a href="https://docs.blender.org/manual/en/latest/animation/constraints/relationship/child_of.html" target="_blank" rel="noopener">Blender 官方 · 接触空间切换 ↗</a><p>先匹配世界变换，再切换跟随。本轮使用复制变换约束，避免抓住或松开时跳位。</p></div><div class="source"><a href="https://docs.blender.org/manual/en/latest/modeling/modifiers/deform/corrective_smooth.html" target="_blank" rel="noopener">Blender 官方 · 局部形变修正 ↗</a><p>连续网格与混合权重先行，再限制范围平滑关节，避免整个衣袖一起缩水。</p></div></div>
<details><summary>实验边界与可编辑文件</summary><p>本轮同时修改人物和动作，属于迭代结果对照。A/B 三分之四机位、比例和 EEVEE 材质流程一致；时长不同，侧视仅用于新版诊断。</p><p>模型与动作由 Blender 脚本制作，非手绘成片或 AI 自动成品。接触是关键帧安排；手指有开合形态键，头发有延迟形态键；未完成动态碰撞、独立手指骨骼、表情和商业级角色修形，未导入 Unity。</p><p><a href="st_hizuru_shoulder_polish.blend">下载可编辑 .blend</a> · <a href="README.md">制作与验证记录</a> · <a href="../face-polish-research-2026-09-21.md">人物教程详表</a> · <a href="../grip-deformation-research-2026-09-21.md">力量感教程详表</a> · <a href="../artist-social-links-2026-09-21.md">论坛与 X 检索记录</a></p><p>找到作者 <a href="https://x.com/AversionReality" target="_blank" rel="noopener">@AversionReality</a>；未读到推文正文。Polycount 本轮返回 403。教程视频仅阅读页面/字幕的条目已分别标注。</p></details>
<footer>《夏日重现》日鹤同人原型研究，非官方作品。保留旧版；本轮不恢复主游戏开发。</footer></main>
<script>const $=id=>document.getElementById(id),a=$('before'),b=$('after'),vids=[a,b];const sources={main:'__REVISED__',side:'__SIDE__'};let playing=false;function stop(){playing=false;vids.forEach(v=>v.pause());$('play').textContent='播放对照'}function display(f){$('seek').value=f;$('frame').textContent=String(f+1).padStart(2,'0')+' / 72'}function seek(f){stop();a.currentTime=Math.min(2.95,f/20);b.currentTime=f/20;display(f)}$('play').onclick=async()=>{if(playing){stop();return}if(b.currentTime>=3.55)seek(0);a.currentTime=Math.min(2.95,b.currentTime);try{await Promise.all(vids.map(v=>v.play()));playing=true;$('play').textContent='暂停'}catch(e){$('status').textContent='播放失败：'+e.message}};$('reset').onclick=()=>seek(0);$('seek').oninput=()=>seek(Number($('seek').value));$('speed').onchange=()=>vids.forEach(v=>v.playbackRate=Number($('speed').value));document.querySelectorAll('[data-frame]').forEach(el=>el.onclick=()=>seek(Number(el.dataset.frame)));$('view').onchange=()=>{const f=Number($('seek').value);stop();b.src=sources[$('view').value];b.addEventListener('loadeddata',()=>{b.currentTime=f/20;b.playbackRate=Number($('speed').value);$('status').textContent=$('view').value==='side'?'横版侧视 · 查看支撑脚、锤头弧线与落点':'三分之四视角 · 与上一版机位一致'},{once:true});b.load()};vids.forEach(v=>{if(v===b)v.addEventListener('ended',stop);v.addEventListener('error',()=>{$('status').textContent='媒体加载失败，请重新打开页面'})});a.addEventListener('loadeddata',()=>{$('status').textContent='本地预览已加载 · 新版 72 帧 / 20 fps / 3.6 秒'});function update(){if(playing){const f=Math.min(71,Math.floor(b.currentTime*20));display(f);if(b.currentTime<2.95 && Math.abs(a.currentTime-b.currentTime)>.12)a.currentTime=b.currentTime}requestAnimationFrame(update)}update();</script></html>'''
for key,name,mime in [('__BASELINE__','baseline.mp4','video/mp4'),('__REVISED__','revised.mp4','video/mp4'),('__SIDE__','side.mp4','video/mp4'),('__SHEET__','keyposes.jpg','image/jpeg'),('__FACES__','face_comparison.jpg','image/jpeg')]:html=html.replace(key,data(name,mime))
(OUT/'comparison.html').write_text(html)
print('Wrote comparison.html, keyposes.jpg, mp4/gif previews')
