from pathlib import Path
import subprocess,base64,json
from PIL import Image,ImageDraw,ImageFont
OUT=Path(__file__).resolve().parent
FF='/opt/homebrew/bin/ffmpeg'
for folder,name in [('frames','revised'),('side_frames','side'),('baseline_frames','baseline')]:
    subprocess.run([FF,'-y','-loglevel','error','-framerate','20','-i',str(OUT/folder/'%04d.png'),'-c:v','libx264','-crf','19','-pix_fmt','yuv420p','-movflags','+faststart',str(OUT/(name+'.mp4'))],check=True)
subprocess.run([FF,'-y','-loglevel','error','-i',str(OUT/'revised.mp4'),'-filter_complex','fps=20,scale=480:-1:flags=lanczos,split[a][b];[a]palettegen=stats_mode=diff[p];[b][p]paletteuse=dither=sierra2_4a','-loop','0',str(OUT/'hammer_art_weight.gif')],check=True)
frames=[1,18,23,27,29,32,44,56]
labels=['01 / CARRY','18 / LOAD','23 / BODY LEADS','27 / ACCELERATE','29 / CONTACT','32 / ABSORB','44 / RECOVER','56 / SHOULDER']
board=Image.new('RGB',(1440,776),'#11191e');draw=ImageDraw.Draw(board)
for i,(f,label) in enumerate(zip(frames,labels)):
    x=(i%4)*360;y=(i//4)*388
    im=Image.open(OUT/'frames'/f'{f:04d}.png').convert('RGB').resize((360,360))
    board.paste(im,(x,y));draw.text((x+12,y+367),label,fill='#dce7e7')
board.save(OUT/'keyposes.jpg',quality=92)

def data(name,mime):return 'data:'+mime+';base64,'+base64.b64encode((OUT/name).read_bytes()).decode()
html='''<!doctype html><html lang="zh-CN" translate="no"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>日鹤 · 人物与力量感试作</title>
<style>*{box-sizing:border-box}body{margin:0;background:#10191e;color:#e7ece9;font:15px/1.7 -apple-system,BlinkMacSystemFont,"PingFang SC",sans-serif}main{max-width:1160px;margin:auto;padding:32px 28px 60px}a{color:#94d0c2}header{display:flex;justify-content:space-between;gap:20px;align-items:end;margin-bottom:22px}h1{font-size:30px;letter-spacing:.02em;margin:5px 0 8px}p{margin:7px 0}.eyebrow{font-size:11px;color:#97b6b7;letter-spacing:3px}header p,.muted{color:#99acb1;font-size:13px}.tag{border:1px solid #46625e;border-radius:99px;padding:5px 12px;color:#b5d7cb;font-size:12px;white-space:nowrap}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.card{background:#1a262c;border:1px solid #2b3b43;border-radius:14px;overflow:hidden}.cardtop{padding:14px 18px;display:flex;align-items:center;justify-content:space-between}.cardtop b{font-size:16px}.cardtop span{color:#91a9af;font-size:12px}video{width:100%;aspect-ratio:1;display:block;background:#263439}.toolbar{margin:22px 0;display:flex;align-items:center;gap:12px;flex-wrap:wrap}button,select{border:1px solid #405259;border-radius:7px;background:#24343a;color:#edf2ef;padding:9px 16px;font:inherit;cursor:pointer}button.primary{background:#b9d8cc;color:#18332c;border-color:#b9d8cc;font-weight:600}input{accent-color:#c1dccf;flex:1;min-width:160px}#frame{font-variant-numeric:tabular-nums;width:65px;color:#b5c9cc}#status{font-size:12px;color:#92b1b7;min-height:24px}.keys{display:flex;gap:7px;flex-wrap:wrap}.keys button{font-size:12px;padding:6px 12px}.callout{display:grid;grid-template-columns:repeat(3,1fr);gap:22px;padding:23px 0;margin:18px 0;border-top:1px solid #304049;border-bottom:1px solid #304049}.callout b{display:block;font-size:14px;margin-bottom:5px}.callout p{font-size:13px;color:#9fb1b5}h2{font-size:19px;margin:27px 0 12px}.sheet{width:100%;border-radius:10px}.sources{display:grid;grid-template-columns:1fr 1fr;gap:10px}.source{padding:14px 17px;background:#1b282e;border:1px solid #30424a;border-radius:10px}.source p{color:#9db0b5;font-size:12px}details{margin-top:22px;color:#a7bbbe;font-size:13px}summary{cursor:pointer}footer{margin-top:25px;color:#829b9e;font-size:12px}@media(max-width:700px){main{padding:20px 14px}.grid,.sources,.callout{grid-template-columns:1fr}header{display:block}h1{font-size:25px}.tag{display:inline-block;margin-top:8px}.toolbar{gap:8px}.cardtop{padding:10px 13px}}</style>
<main><header><div><div class="eyebrow">SUMMER MEMORIES / MOTION STUDY 04</div><h1>人物辨识度，与重锤的重量</h1><p>长发 · 眼镜 · 西装 / 身体先动 → 快砸 → 接触卸力 → 回肩</p></div><span class="tag">可编辑动画试作 · 2026.09.21</span></header>
<div class="grid"><section class="card"><div class="cardtop"><b>A · 上一版骨架人偶</b><span>保留原动作 · 重渲同机位</span></div><video id="before" muted playsinline preload="auto" src="__BASELINE__"></video></section><section class="card"><div class="cardtop"><b id="rightTitle">B · 人物与动作修改</b><select id="view" aria-label="新版视角"><option value="main">三分之四视角</option><option value="side">横版侧视</option></select></div><video id="after" muted playsinline preload="auto" src="__REVISED__"></video></section></div>
<div class="toolbar"><button id="play" class="primary">播放对照</button><button id="reset">回到开头</button><select id="speed" aria-label="播放速度"><option value="1">1× 原速</option><option value=".5">0.5× 慢放</option></select><input id="seek" aria-label="停帧" type="range" min="0" max="59" step="1" value="0"><span id="frame">01 / 60</span></div>
<div class="keys"><button data-frame="0">肩扛 · 01</button><button data-frame="17">蓄力 · 18</button><button data-frame="22">身体启动 · 23</button><button data-frame="28">接触 · 29</button><button data-frame="31">卸力 · 32</button><button data-frame="43">回收 · 44</button></div><p id="status">加载本地预览…</p>
<div class="callout"><div><b>先把人物做出来</b><p>重做脸部、眼镜、宽发束、西装和鞋；限制配色与明暗层次，检查动作中的轮廓。</p></div><div><b>给打击一个落点</b><p>第 29 帧接触靶面。身体继续压低，锤头短回弹，再慢慢收回；预览未加震屏或特效。</p></div><div><b>连续，但仍需打磨</b><p>沿用可编辑骨架，脚与握点受约束。面部、肩肘形变和扛肩表演仍是练习稿水准。</p></div></div>
<h2>按正常速度看片，再逐帧检查</h2><img class="sheet" src="__SHEET__" alt="肩扛、蓄力、身体启动、加速、接触、卸力、回收关键姿势对照">
<h2>本轮实际读到的教程与社区分享</h2><div class="sources"><div class="source"><a href="https://www.aversionofreality.com/blog/2021/1/22/reimu-hakurei-workflow-test" target="_blank" rel="noopener">aVersionOfReality · 角色制作拆解 ↗</a><p>长发分束控制、材质分层，以及为镜头修形。已读作者全文。</p></div><div class="source"><a href="https://blenderartists.org/t/stylized-hair-geometry-nodes/1406121" target="_blank" rel="noopener">BlenderArtists · 风格化发束节点 ↗</a><p>曲线、半径与截面控制。已读帖子并查看节点图，本轮借鉴宽窄形体。</p></div><div class="source"><a href="https://blog.animschool.edu/2025/08/08/blocking-plus-workflow-timing/" target="_blank" rel="noopener">AnimSchool · Blocking 与节奏 ↗</a><p>先做关键姿态，再安排蓄力、爆发与动量吸收。已读正文摘要。</p></div><div class="source"><a href="https://www.animatorisland.com/physics-in-animation-action-reaction/" target="_blank" rel="noopener">Animator Island · 接触与反作用 ↗</a><p>打击者也要承受接触带来的减速。已读完整文字。</p></div></div>
<details><summary>实验边界与可编辑文件</summary><p>本轮同时修改人物、动作、材质与靶面，属于迭代结果对照，不能证明某个单独因素的贡献。A 保留上一版工作台材质；A/B 三分之四机位、比例和时长一致，侧视仅用于新版诊断。</p><p>模型与动作由 Blender 脚本制作，非手绘成片或 AI 自动成品。接触是关键帧安排，手掌随道具、头发用形态键；未完成动态碰撞、独立手指、表情和商业级角色修形，未导入 Unity。</p><p><a href="st_hizuru_weight_study.blend">下载可编辑 .blend</a> · <a href="README.md">制作与验证记录</a> · <a href="../character-art-tutorials-2026-09-21.md">人物教程详表</a> · <a href="../weight-community-tutorials-2026-09-21.md">力量感教程详表</a> · <a href="../artist-social-links-2026-09-21.md">论坛与 X 检索记录</a></p><p>找到作者 <a href="https://x.com/AversionReality" target="_blank" rel="noopener">@AversionReality</a>；未读到推文正文。Polycount 本轮返回 403。教程视频仅阅读页面/字幕的条目已分别标注。</p></details>
<footer>《夏日重现》日鹤同人原型研究，非官方作品。保留旧版；本轮不恢复主游戏开发。</footer></main>
<script>const $=id=>document.getElementById(id),a=$('before'),b=$('after'),vids=[a,b];const sources={main:'__REVISED__',side:'__SIDE__'};let playing=false;function stop(){playing=false;vids.forEach(v=>v.pause());$('play').textContent='播放对照'}function display(f){$('seek').value=f;$('frame').textContent=String(f+1).padStart(2,'0')+' / 60'}function seek(f){stop();vids.forEach(v=>v.currentTime=f/20);display(f)}$('play').onclick=async()=>{if(playing){stop();return}if(a.currentTime>=2.95)seek(0);b.currentTime=a.currentTime;try{await Promise.all(vids.map(v=>v.play()));playing=true;$('play').textContent='暂停'}catch(e){$('status').textContent='播放失败：'+e.message}};$('reset').onclick=()=>seek(0);$('seek').oninput=()=>seek(Number($('seek').value));$('speed').onchange=()=>vids.forEach(v=>v.playbackRate=Number($('speed').value));document.querySelectorAll('[data-frame]').forEach(el=>el.onclick=()=>seek(Number(el.dataset.frame)));$('view').onchange=()=>{const f=Number($('seek').value);stop();b.src=sources[$('view').value];b.addEventListener('loadeddata',()=>{b.currentTime=f/20;b.playbackRate=Number($('speed').value);$('status').textContent=$('view').value==='side'?'横版侧视 · 查看支撑脚、锤头弧线与落点':'三分之四视角 · 与上一版机位一致'},{once:true});b.load()};vids.forEach(v=>{v.addEventListener('ended',stop);v.addEventListener('error',()=>{$('status').textContent='媒体加载失败，请重新打开页面'})});a.addEventListener('loadeddata',()=>{$('status').textContent='本地预览已加载 · 60 帧 / 20 fps / 3 秒'});function update(){if(playing){const f=Math.min(59,Math.floor(a.currentTime*20));display(f);if(Math.abs(a.currentTime-b.currentTime)>.12)b.currentTime=a.currentTime}requestAnimationFrame(update)}update();</script></html>'''
for key,name,mime in [('__BASELINE__','baseline.mp4','video/mp4'),('__REVISED__','revised.mp4','video/mp4'),('__SIDE__','side.mp4','video/mp4'),('__SHEET__','keyposes.jpg','image/jpeg')]:html=html.replace(key,data(name,mime))
(OUT/'comparison.html').write_text(html)
print('Wrote comparison.html, keyposes.jpg, mp4/gif previews')
